name: Test

on:
  push:
    branches: '*'
  pull_request:
    branches: [ net5 ]

jobs:
  Build:
    name: Build
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@master

    - name: Build
      run: msbuild SmartTaskbar.sln
      shell: pwsh